# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
  python: python3.12

repos:
  - repo: local
    hooks:
      - id: ruff
        name: Format with Ruff
        entry: uv --project backend run ruff
        require_serial: true
        language: python
        types: [ python ]
        args: [ --config, backend/pyproject.toml, check, backend/yet_another_calendar, --fix, --exit-non-zero-on-fix ]
        additional_dependencies: [ uv ]

      - id: mypy
        name: mypy
        entry: uv --project backend run mypy
        require_serial: true
        pass_filenames: true
        language: python
        types: [ python ]
        'types_or': [ python, pyi ]
        args: [
          "--explicit-package-bases",
          "--config-file=backend/pyproject.toml",
        ]
        additional_dependencies: [ uv ]

      - id: pytest
        name: pytest
        entry: uv --project backend run pytest -v
        require_serial: true
        pass_filenames: true
        language: python
        types: [ python ]
        'types_or': [ python, pyi ]
        args: [
          "--cov=backend/yet_another_calendar/web",
          "./backend/yet_another_calendar/tests/",
        ]
        additional_dependencies: [ uv ]
