name: build and deploy

on:
  push:
    branches:
      - fix_cicd_speed
    paths-ignore:
      - "README.md"
  workflow_dispatch:

env:
  REGISTRY_URL: ghcr.io
  REGISTRY_USERNAME: azamatkomaev
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  IMAGE_TAG: ${{ github.sha }}

  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_PORT: ${{ secrets.SSH_PORT }}

  S3_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT_URL }}
  S3_REGION: ${{ secrets.S3_REGION }}
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  ACCESS_KEY: ${{ secrets.ACCESS_KEY }}


jobs:
  lint-test:
    uses: depocoder/YetAnotherCalendar/.github/workflows/lint-and-test.yaml@main

  build:
    runs-on: ubuntu-latest
    needs: [ lint-test ]
    steps:
      - uses: actions/checkout@v4
      - name: Login with Github Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}
      - name: Add custom builder
        run: |
          docker buildx create \
            --name container-builder \
            --driver docker-container \
            --bootstrap --use
      - name: Build & Publish backend to Github Container registry
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 --push ./backend \
                       --tag $REGISTRY_URL/$REGISTRY_USERNAME/yet_another_calendar_backend:latest \
                       --tag $REGISTRY_URL/$REGISTRY_USERNAME/yet_another_calendar_backend:$IMAGE_TAG \
                       --cache-to   type=s3,endpoint_url=$S3_ENDPOINT_URL,region=$S3_REGION,bucket=$BUCKET_NAME,name=calendar_backend,access_key_id=$ACCESS_KEY,secret_access_key=$SECRET_KEY \
                       --cache-from type=s3,endpoint_url=$S3_ENDPOINT_URL,region=$S3_REGION,bucket=$BUCKET_NAME,name=calendar_backend,access_key_id=$ACCESS_KEY,secret_access_key=$SECRET_KEY

      - name: Build & Publish frontend to Github Container registry
        run: |
          docker buildx build --platform linux/amd64 --push ./frontend \
                       --tag $REGISTRY_URL/$REGISTRY_USERNAME/yet_another_calendar_frontend:latest \
                       --tag $REGISTRY_URL/$REGISTRY_USERNAME/yet_another_calendar_frontend:$IMAGE_TAG \
                       --cache-to   type=s3,endpoint_url=$S3_ENDPOINT_URL,blobs_prefix=frontend_amd64_blobs,region=$S3_REGION,bucket=$BUCKET_NAME,name=calendar_frontend_amd64,access_key_id=$ACCESS_KEY,secret_access_key=$SECRET_KEY \
                       --cache-from type=s3,endpoint_url=$S3_ENDPOINT_URL,blobs_prefix=frontend_amd64_blobs,region=$S3_REGION,bucket=$BUCKET_NAME,name=calendar_frontend_amd64,access_key_id=$ACCESS_KEY,secret_access_key=$SECRET_KEY
          docker buildx build --platform linux/arm64 --push ./frontend \
                       --tag $REGISTRY_URL/$REGISTRY_USERNAME/yet_another_calendar_frontend:latest \
                       --tag $REGISTRY_URL/$REGISTRY_USERNAME/yet_another_calendar_frontend:$IMAGE_TAG \
                       --cache-to   type=s3,endpoint_url=$S3_ENDPOINT_URL,blobs_prefix=frontend_arm64_blobs,region=$S3_REGION,bucket=$BUCKET_NAME,name=calendar_frontend_arm64,access_key_id=$ACCESS_KEY,secret_access_key=$SECRET_KEY \
                       --cache-from type=s3,endpoint_url=$S3_ENDPOINT_URL,blobs_prefix=frontend_arm64_blobs,region=$S3_REGION,bucket=$BUCKET_NAME,name=calendar_frontend_arm64,access_key_id=$ACCESS_KEY,secret_access_key=$SECRET_KEY
