name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.5

      - name: Configure Poetry
        run: |
          uv sync
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: uv sync --project backend

      - name: Run linters
        run: |
          cd backend
          uv run ruff check yet_another_calendar
          uv run mypy yet_another_calendar
          
